# AUTOGENERATED - DO NOT EDIT

general {
  gaps_in = {{gaps_in}}
  gaps_out = {{gaps_out}}
  border_size = {{border_size}}

  col.active_border = {{border_active}}
  col.inactive_border = {{border_inactive}}

  layout = {{layout}}
}

decoration {
  rounding = {{rounding}}
  active_opacity = {{active_opacity}}
  inactive_opacity = {{inactive_opacity}}

  shadow {
    enabled = {{shadow_enabled}}
    range = {{shadow_range}}
    render_power = {{shadow_power}}
    color = {{shadow_color}}
  }

  blur {
    enabled = {{blur_enabled}}
    size = {{blur_size}}
    passes = {{blur_passes}}
    vibrancy = {{blur_vibrancy}}
  }
}

# Layer rules
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.2, match:namespace waybar

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0.2, match:namespace wofi

layerrule = blur on, match:class wlogout
layerrule = ignore_alpha 0.2, match:class wlogout