#   _                       _                  _ 
#  | |                     | |                | |
#  | |__  _   _ ____   ____| | _____ ____   __| |
#  |  _ \| | | |  _ \ / ___) |(____ |  _ \ / _  |
#  | | | | |_| | |_| | |   | |/ ___ | | | ( (_| |
#  |_| |_|\__  |  __/|_|    \_)_____|_| |_|\____|
#        (____/|_|                               
#
# ====================== 
# Theme Switcher made by enes-less
# ======================
#
# ======================
# CURRENTLY APPLIED THEME
# ======================
# DO NOT REMOVE THIS LINE. THIS CONF IS WHAT THEME SWITCHER PROVIDES FOR HYPRLAND.
source = ~/.config/hypr/generated-theme.conf

# ======================
# MODULAR CONFIG
# ======================
# You can edit the configurations from each file.

source = ~/.config/hypr/hyprland-config/env_vars.conf
source = ~/.config/hypr/hyprland-config/monitor.conf
source = ~/.config/hypr/hyprland-config/input.conf
source = ~/.config/hypr/hyprland-config/gestures.conf
source = ~/.config/hypr/hyprland-config/layout.conf
source = ~/.config/hypr/hyprland-config/decoration.conf
source = ~/.config/hypr/hyprland-config/animations.conf
source = ~/.config/hypr/hyprland-config/window-rules.conf
source = ~/.config/hypr/hyprland-config/workspaces.conf
source = ~/.config/hypr/hyprland-config/keybinds.conf
source = ~/.config/hypr/hyprland-config/programs.conf
source = ~/.config/hypr/hyprland-config/autostart.conf
source = ~/.config/hypr/hyprland-config/misc.conf