# ======================
# ANIMATIONS
# ======================
# These animations are designed to be soft. You can edit the values however you want.

animations {
    enabled = yes

    bezier = softEase, 0.33, 1, 0.68, 1
    bezier = smooth,   0.4, 0, 0.2, 1
    bezier = gentle,   0.25, 0.1, 0.25, 1

    animation = global,     1, 8,  default
    animation = windows,    1, 3.5, smooth
    animation = windowsIn,  1, 3.5, smooth, popin 85%
    animation = windowsOut, 1, 2,   softEase, popin 85%
    animation = fade,       1, 3,   gentle
    animation = layers,     1, 3,   smooth
    animation = workspaces, 1, 5,   smooth, fade
}