# ======================
# GESTURES
# ======================
# I added 2 gestures for my Magic Trackpad. Feel free to edit/delete.

gesture = 3, horizontal, workspace
gesture = 3, down, mod: ALT, close