# ======================
# PROGRAMS
# ======================
# Define programs you use.

$terminal = KITTY_LISTEN_ON=unix:/tmp/kitty.sock kitty --title Kitty
$fileManager = nautilus
$menu = wofi --show drun
$mainMod = SUPER