# ======================
# WINDOW RULES
# ======================
# Define your window rules.

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    float = yes
    move = 20 monitor_h-120
}

# Feel free to delete this. This is for hypridle to not go idle when Zen Browser is working.
# Just a random preference of mine.
windowrule {
    name = keep-zen-awake
    match:class = zen.*
    idle_inhibit = fullscreen
}